name: CI

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest]
                ghc: ["9.12.2"]

        steps:
            - uses: actions/checkout@v4

            - name: Setup Haskell
              uses: haskell-actions/setup@v2
              with:
                  ghc-version: ${{ matrix.ghc }}
                  cabal-version: "latest"
                  enable-stack: false

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cabal
                  key: ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
                  restore-keys: |
                      ${{ runner.os }}-cabal-${{ matrix.ghc }}-
                      ${{ runner.os }}-cabal-

            - name: Update cabal package index
              run: cabal update

            - name: Build project
              run: cabal build

            - name: Run tests
              run: cabal test
